/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["executeQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuery"];
        put?: never;
        post?: never;
        delete: operations["cancelQuery"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/tables/{database}/{table}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["describeTable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startDiscovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/tables/{database}/{table}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTableStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/tables/{database}/{table}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTableHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEtls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/{name}/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlGrid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/{name}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEtlRuns"];
        put?: never;
        post: operations["runEtl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/{name}/schedule/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeEtlSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/{name}/schedule/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pauseEtlSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/runs/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlRunLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/runs/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlRunTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/runs/{id}/steps/{task_run}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlRunStep"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TableField: {
            name: string;
            type: string;
            nullable: boolean;
        };
        TableDetail: {
            database: string;
            name: string;
            source: string;
            path: string;
            labels: {
                [key: string]: string;
            };
            delta_version: number;
            fields: components["schemas"]["TableField"][];
        };
        QueryRequest: {
            sql: string;
            max_rows?: number;
        };
        QueryError: {
            code: string;
            message: string;
        };
        QueryStatus: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            state: "running" | "completed" | "failed" | "cancelled";
            rows: number;
            bytes: number;
            truncated: boolean;
            snapshots: {
                [key: string]: number;
            };
            error?: components["schemas"]["QueryError"] | null;
        };
        /** @description Normalised client-side by @periplo/core/api; never inspected by screens. */
        ErrorEnvelope: {
            [key: string]: unknown;
        };
        LabelValue: {
            value: string;
            title?: string;
            description?: string;
            order?: number;
        };
        CatalogTable: {
            database: string;
            name: string;
            source: string;
            path: string;
            labels: {
                [key: string]: string;
            };
            unlabeled: string[];
        };
        Conflict: {
            database: string;
            name: string;
            paths: string[];
        };
        Catalog: {
            /** Format: date-time */
            published_at: string;
            /** @description Labels the explorer nests by, outermost first. Empty groups by database alone. */
            group_by: string[];
            label_values: {
                [key: string]: components["schemas"]["LabelValue"][];
            };
            tables: components["schemas"]["CatalogTable"][];
            conflicts: components["schemas"]["Conflict"][];
            links?: components["schemas"]["LinkTemplate"][];
        };
        DiscoveryReport: {
            /** @enum {string} */
            state: "ok" | "partial" | "failed";
            /** Format: date-time */
            started_at: string;
            duration_ms: number;
            tables: number;
            listed_folders: number;
            branches_without_table: number;
            error?: string | null;
        };
        Source: {
            name: string;
            location: string;
            template: string;
            report: components["schemas"]["DiscoveryReport"];
        };
        DiscoveryState: {
            /** @enum {string} */
            state: "idle" | "running";
            /** Format: date-time */
            started_at?: string | null;
        };
        SourceList: {
            discovery: components["schemas"]["DiscoveryState"];
            /** Format: date-time */
            published_at: string;
            sources: components["schemas"]["Source"][];
        };
        ColumnStats: {
            name: string;
            nulls?: number;
            min?: string;
            max?: string;
        };
        TableStats: {
            rows: number;
            bytes: number;
            files: number;
            partition_columns: string[];
            columns: components["schemas"]["ColumnStats"][];
            /** @description The heaviest partitions in value order, read from the log. May be fewer than partitions_total. */
            partitions?: components["schemas"]["PartitionStats"][];
            partitions_total?: number;
        };
        PartitionStats: {
            values: {
                [key: string]: string | null;
            };
            rows: number;
            bytes: number;
            files: number;
        };
        HistoryEntry: {
            version: number;
            /** Format: date-time */
            timestamp: string;
            operation: string;
            parameters: {
                [key: string]: unknown;
            };
            metrics: {
                [key: string]: unknown;
            };
            extra: {
                [key: string]: unknown;
            };
        };
        TableHistory: {
            entries: components["schemas"]["HistoryEntry"][];
        };
        LinkTemplate: {
            label: string;
            key: string;
            url_template: string;
        };
        EtlStatus: {
            configured: boolean;
            operate_enabled: boolean;
        };
        Schedule: {
            /** @enum {string} */
            kind: "cron" | "interval" | "rrule";
            cron: string | null;
            interval_seconds: number | null;
            timezone: string | null;
            active: boolean;
        };
        FlowRun: {
            id: string;
            name: string;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            state_message: string | null;
            /** Format: date-time */
            expected_start_at: string | null;
            /** Format: date-time */
            start_at: string | null;
            /** Format: date-time */
            end_at: string | null;
            duration_seconds: number;
            created_by: string | null;
            run_count: number;
            retries: number;
            retry_delay_seconds: number;
            /**
             * @description scheduled when the run carries the orchestrator's own auto-scheduled marker
             * @enum {string}
             */
            trigger: "scheduled" | "manual";
            /** @description A deep link into the orchestrator's own UI, or null when none is configured. */
            external_url: string | null;
            /** @description One entry per attempt when run_count > 1; null when run_count <= 1 or the response's attempt budget was already spent. */
            attempts: components["schemas"]["RunAttempt"][] | null;
        };
        RunAttempt: {
            index: number;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string | null;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            duration_seconds: number | null;
        };
        RecentRun: {
            id: string;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            /** Format: date-time */
            start_at: string | null;
            /** Format: date-time */
            end_at: string | null;
            /** @description Copied from the FlowRun it derives from; same rules as FlowRun.attempts. */
            attempts: components["schemas"]["RunAttempt"][] | null;
        };
        Etl: {
            id: string;
            name: string;
            flow_name: string;
            description: string | null;
            tags: string[];
            paused: boolean;
            schedule: components["schemas"]["Schedule"] | null;
            parameters: {
                [key: string]: unknown;
            };
            last_run: components["schemas"]["FlowRun"] | null;
            recent: components["schemas"]["RecentRun"][];
            /** Format: date-time */
            next_run_at: string | null;
            schedule_inactive: boolean;
            cadence: string | null;
            mode: string | null;
            /** @description processes appears in parameter_openapi_schema.properties; gates "Re-run from failed process" */
            accepts_processes: boolean;
            /** @description A deep link into the orchestrator's own UI, or null when none is configured. */
            external_url: string | null;
        };
        /** @description Where a running run is right now: its process, step, and position among them. total counts processes seen so far in this run, not the deployment's typical process count (documented limitation). */
        EtlCurrent: {
            process: string | null;
            step: string | null;
            index: number;
            total: number;
        };
        RunningRun: {
            id: string;
            name: string;
            etl: string;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            /** Format: date-time */
            start_at: string | null;
            created_by: string | null;
            /** @enum {string} */
            trigger: "scheduled" | "manual";
            current: components["schemas"]["EtlCurrent"] | null;
            /** @description Median duration of the deployment's COMPLETED entries in recent. */
            typical_seconds: number | null;
        };
        EtlUpcoming: {
            etl: string;
            /** Format: date-time */
            expected_start_at: string;
        };
        EtlHistoryBucket: {
            /** Format: date-time */
            start: string;
            completed: number;
            failed: number;
            running: number;
        };
        /** @description One window of the dashboard's pulse: bucketed run counts, oldest to newest. */
        EtlHistory: {
            /** @enum {string} */
            interval: "1h" | "1d";
            buckets: components["schemas"]["EtlHistoryBucket"][];
            /** @description SCHEDULED runs due in the next 6h, at most 50, soonest first. */
            upcoming: components["schemas"]["EtlUpcoming"][];
            median_seconds: number | null;
        };
        Summary: {
            running: number;
            failed_24h: number;
            completed_24h: number;
            history: components["schemas"]["EtlHistory"];
            history_7d: components["schemas"]["EtlHistory"];
        };
        EtlList: {
            etls: components["schemas"]["Etl"][];
            summary: components["schemas"]["Summary"];
            running: components["schemas"]["RunningRun"][];
            /** @description running was capped at 20 entries. */
            running_truncated: boolean;
        };
        RunList: {
            runs: components["schemas"]["FlowRun"][];
        };
        RunDetail: components["schemas"]["FlowRun"] & {
            parameters: {
                [key: string]: unknown;
            };
            deployment_id: string | null;
            deployment_name: string | null;
            flow_name: string;
            /** @description state in COMPLETED, FAILED, CANCELLED, CRASHED */
            terminal: boolean;
        };
        LogEntry: {
            id: string;
            /** Format: date-time */
            timestamp: string;
            level: number;
            level_name: string;
            message: string;
            /** @description Starts with one of PERIPLO_ETL_LOG_NOISE's prefixes; folded by default in the web. */
            noise: boolean;
            /** @description Opaque id of the step or process that logged the line (as in RunTasks); null for run-level lines. */
            task_run_id?: string | null;
        };
        /** @enum {string} */
        StepState: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING" | "INTERRUPTED";
        Step: {
            name: string;
            task_run_id: string;
            state: components["schemas"]["StepState"];
            /** Format: date-time */
            start_at: string | null;
            /** Format: date-time */
            end_at: string | null;
            duration_seconds: number | null;
        };
        Process: {
            name: string | null;
            task_run_id: string | null;
            state: components["schemas"]["StepState"];
            /** Format: date-time */
            start_at: string | null;
            /** Format: date-time */
            end_at: string | null;
            duration_seconds: number | null;
            expected_steps: number | null;
            steps: components["schemas"]["Step"][];
        };
        GridCell: {
            process: string;
            state: components["schemas"]["StepState"];
            duration_seconds: number | null;
        };
        GridRun: {
            id: string;
            name: string;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            /** Format: date-time */
            start_at: string | null;
            duration_seconds: number;
            cells: components["schemas"]["GridCell"][];
        };
        RunGrid: {
            /** @description Oldest to newest, left to right. */
            runs: components["schemas"]["GridRun"][];
            /** @description Order of first appearance in the most recent run that has any, then any others. */
            processes: string[];
            /** @description A marker, failed-step or mark query hit its hard page cap before exhausting. */
            truncated: boolean;
        };
        Attempt: {
            number: number;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string | null;
            message: string | null;
            processes: components["schemas"]["Process"][];
        };
        RunTasks: {
            attempts: components["schemas"]["Attempt"][];
            expected_steps_known: boolean;
        };
        StepFacts: {
            reads: string[];
            writes: string[];
            rows: number | null;
            delta_version: number | null;
        };
        StepDetail: {
            step: components["schemas"]["Step"];
            process: string | null;
            facts: components["schemas"]["StepFacts"];
            logs: components["schemas"]["LogPage"];
        };
        LogPage: {
            entries: components["schemas"]["LogEntry"][];
            /** @description Raw timestamp of the last entry, the received `after` if the page was empty, else null. */
            next: string | null;
            /** @description True when the page came full (entries.length == limit). */
            truncated: boolean;
        };
        RunRequest: {
            /** @description null runs with the deployment's own parameters. */
            parameters?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    executeQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Arrow IPC stream */
            200: {
                headers: {
                    "X-Query-Id": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.apache.arrow.stream": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getQuery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    cancelQuery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested or already terminal */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    describeTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                database: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Table */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sources and discovery state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    startDiscovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovery started or already running */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getTableStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                database: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the Delta log knows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableStats"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getTableHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                database: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest commits, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableHistory"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integration status; never touches the orchestrator */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtlStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listEtls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployments visible to Periplo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtlList"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlGrid: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The most recent non-SCHEDULED runs of the deployment as a process x run matrix, oldest to newest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunGrid"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Ambiguous deployment name (etl_ambiguous) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listEtlRuns: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs, most recent first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Ambiguous deployment name (etl_ambiguous) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    runEtl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Run created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description The orchestrator rejected the request (etl_rejected) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Operating ETLs is disabled (etl_operate_disabled) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Ambiguous deployment name (etl_ambiguous) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    resumeEtlSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every schedule reactivated (and the deployment un-paused, if it was) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Etl"];
                };
            };
            /** @description The deployment has no schedule (etl_rejected) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Operating ETLs is disabled (etl_operate_disabled) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Ambiguous deployment name (etl_ambiguous) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    pauseEtlSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every schedule deactivated (the inverse of loom's failure hook) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Etl"];
                };
            };
            /** @description The deployment has no schedule (etl_rejected) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Operating ETLs is disabled (etl_operate_disabled) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Ambiguous deployment name (etl_ambiguous) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlRunLogs: {
        parameters: {
            query?: {
                /** @description The `next` of a previous page, opaque to the client; lines with timestamp >= after, ascending. */
                after?: string;
                limit?: number;
                /** @description Repeatable, up to 100 UUIDs. Without it: flow-level lines only. With one or more: those task runs' own lines (several make up a process's scope: its marker plus its steps). */
                task_run?: string[];
                /** @description The orchestrator's own log text search, sent as a quoted phrase; at most 200 characters. */
                q?: string;
                /** @description A floor on log level. */
                min_level?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log page; without `after`, the last `limit` lines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogPage"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlRunTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run's attempts, grouped into processes and steps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTasks"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlRunStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                task_run: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One step: its facts and the first page of its own logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepDetail"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run/step (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
