/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["executeQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuery"];
        put?: never;
        post?: never;
        delete: operations["cancelQuery"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/tables/{database}/{table}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["describeTable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startDiscovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/tables/{database}/{table}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTableStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/tables/{database}/{table}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTableHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEtls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/{name}/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlGrid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/{name}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEtlRuns"];
        put?: never;
        post: operations["runEtl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/{name}/schedule/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeEtlSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/{name}/schedule/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pauseEtlSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/{name}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveEtl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/{name}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreEtl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelEtlRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/runs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryEtlRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/runs/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlRunLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/runs/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlRunTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etl/runs/{id}/steps/{task_run}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEtlRunStep"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TableField: {
            name: string;
            type: string;
            nullable: boolean;
        };
        TableDetail: {
            database: string;
            name: string;
            source: string;
            path: string;
            labels: {
                [key: string]: string;
            };
            delta_version: number;
            fields: components["schemas"]["TableField"][];
        };
        QueryRequest: {
            sql: string;
            max_rows?: number;
        };
        QueryError: {
            code: string;
            message: string;
        };
        QueryStatus: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            state: "running" | "completed" | "failed" | "cancelled";
            rows: number;
            bytes: number;
            truncated: boolean;
            snapshots: {
                [key: string]: number;
            };
            error?: components["schemas"]["QueryError"] | null;
        };
        /** @description Normalised client-side by @periplo/core/api; never inspected by screens. */
        ErrorEnvelope: {
            [key: string]: unknown;
        };
        LabelValue: {
            value: string;
            title?: string;
            description?: string;
            order?: number;
        };
        CatalogTable: {
            database: string;
            name: string;
            source: string;
            path: string;
            labels: {
                [key: string]: string;
            };
            unlabeled: string[];
        };
        Conflict: {
            database: string;
            name: string;
            paths: string[];
        };
        Catalog: {
            /** Format: date-time */
            published_at: string;
            /** @description Labels the explorer nests by, outermost first. Empty groups by database alone. */
            group_by: string[];
            label_values: {
                [key: string]: components["schemas"]["LabelValue"][];
            };
            tables: components["schemas"]["CatalogTable"][];
            conflicts: components["schemas"]["Conflict"][];
            links?: components["schemas"]["LinkTemplate"][];
        };
        DiscoveryReport: {
            /** @enum {string} */
            state: "ok" | "partial" | "failed";
            /** Format: date-time */
            started_at: string;
            duration_ms: number;
            tables: number;
            listed_folders: number;
            branches_without_table: number;
            error?: string | null;
        };
        Source: {
            name: string;
            location: string;
            template: string;
            report: components["schemas"]["DiscoveryReport"];
        };
        DiscoveryState: {
            /** @enum {string} */
            state: "idle" | "running";
            /** Format: date-time */
            started_at?: string | null;
        };
        SourceList: {
            discovery: components["schemas"]["DiscoveryState"];
            /** Format: date-time */
            published_at: string;
            sources: components["schemas"]["Source"][];
        };
        ColumnStats: {
            name: string;
            nulls?: number;
            min?: string;
            max?: string;
        };
        TableStats: {
            rows: number;
            bytes: number;
            files: number;
            partition_columns: string[];
            columns: components["schemas"]["ColumnStats"][];
            /** @description The heaviest partitions in value order, read from the log. May be fewer than partitions_total. */
            partitions?: components["schemas"]["PartitionStats"][];
            partitions_total?: number;
        };
        PartitionStats: {
            values: {
                [key: string]: string | null;
            };
            rows: number;
            bytes: number;
            files: number;
        };
        HistoryEntry: {
            version: number;
            /** Format: date-time */
            timestamp: string;
            operation: string;
            parameters: {
                [key: string]: unknown;
            };
            metrics: {
                [key: string]: unknown;
            };
            extra: {
                [key: string]: unknown;
            };
        };
        TableHistory: {
            entries: components["schemas"]["HistoryEntry"][];
        };
        LinkTemplate: {
            label: string;
            key: string;
            url_template: string;
        };
        EtlStatus: {
            configured: boolean;
            operate_enabled: boolean;
            /** @description Whether the caller may archive and restore ETLs (kept by Periplo; nothing changes in the orchestrator). The open-core default follows PERIPLO_ETL_ALLOW_ARCHIVE, else PERIPLO_ETL_ALLOW_OPERATE. */
            archive_enabled: boolean;
            /**
             * @description process: archives are kept in this API process, lost on restart and not shared between API workers (the open-core store); durable: a store that outlives it.
             * @enum {string}
             */
            archive_mode: "process" | "durable";
            /** @description How the installation names the facets its tags form, by tag prefix (PERIPLO_ETL_FACETS); empty when it configures none. Nothing in the console names a prefix: every prefix:value tag forms a facet, and tags without a colon one Labels facet. */
            facets: {
                [key: string]: components["schemas"]["FacetConfig"];
            };
        };
        FacetConfig: {
            /** @description Its name; the prefix, humanised, when null. */
            label: string | null;
            /** @description Its place among the facets, lowest first; unset ones follow by how many ETLs carry the prefix. */
            order: number | null;
            /** @description Never offered as a filter, a grouping or on an ETL's page. */
            hidden: boolean;
            /** @description reads/writes: lineage. expects_schedule: an ETL carrying one of values should be scheduled. */
            role: ("reads" | "writes" | "expects_schedule") | null;
            /** @description Required by, and only allowed with, role expects_schedule. */
            values: string[] | null;
        };
        ArchiveMark: {
            /** Format: date-time */
            at: string;
            /** @description The caller's subject; null without a login. */
            by: string | null;
            reason: string | null;
        };
        ArchiveState: {
            name: string;
            archived: components["schemas"]["ArchiveMark"] | null;
        };
        ArchiveRequest: {
            reason?: string | null;
        };
        Schedule: {
            /** @enum {string} */
            kind: "cron" | "interval" | "rrule";
            cron: string | null;
            interval_seconds: number | null;
            timezone: string | null;
            active: boolean;
        };
        /** @description What starts a chained ETL: another ETL's run completing. */
        EtlTrigger: {
            /** @description The ETL whose completed run starts this one. */
            etl: string;
            /** @enum {string} */
            on: "completed";
            /** @description The parameters the trigger copies from the upstream run onto the run it starts, by name, sorted. */
            passes: string[];
            /** @description The parameters the trigger sets to a constant on the run it starts, with their value. One set by any other template is in neither. */
            sets: {
                [key: string]: unknown;
            };
        };
        FlowRun: {
            id: string;
            name: string;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            state_message: string | null;
            /** Format: date-time */
            expected_start_at: string | null;
            /** Format: date-time */
            start_at: string | null;
            /**
             * Format: date-time
             * @description When its current (or, once finished, its last) attempt started. start_at is the orchestrator's own start, which a retry from its UI keeps at the first attempt's: elapsed time, slowness and a live bar run from this one. null while the run waits to start, a retried run waiting for its next attempt included. For a finished retried run whose attempts were not read, the first start.
             */
            attempt_started_at: string | null;
            /**
             * Format: date-time
             * @description Since when it has waited for its current attempt to start: when it was due, or, for a retried run waiting for its next attempt, when it entered its current state or, if later, when that state is due (a retry delay); the orchestrator keeps the first attempt's expected start. The console calls a run stuck from this.
             */
            waiting_since: string | null;
            /** Format: date-time */
            end_at: string | null;
            duration_seconds: number;
            /** @description Who created the run, as the orchestrator names them. null for a run an automation created: its name can carry a hidden upstream ETL's name, so the console says "Triggered by X › run" from triggered_by_run instead. */
            created_by: string | null;
            run_count: number;
            retries: number;
            retry_delay_seconds: number;
            /**
             * @description automation when an orchestrator automation created the run (a chained ETL), scheduled when it carries the orchestrator's own auto-scheduled marker, else manual
             * @enum {string}
             */
            trigger: "scheduled" | "manual" | "automation";
            /** @description A deep link into the orchestrator's own UI, or null when none is configured. */
            external_url: string | null;
            /** @description One entry per attempt when run_count > 1; null when run_count <= 1 or the response's attempt budget was already spent. */
            attempts: components["schemas"]["RunAttempt"][] | null;
        };
        RunAttempt: {
            index: number;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string | null;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            duration_seconds: number | null;
        };
        RecentRun: {
            id: string;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            /** @description How many attempts the run took (FlowRun.run_count): known even when attempts is not, so a retried run is always marked as such. */
            run_count: number;
            /**
             * Format: date-time
             * @description When it was due: dates a run that never started (cancelled before it did).
             */
            expected_start_at: string | null;
            /** Format: date-time */
            start_at: string | null;
            /**
             * Format: date-time
             * @description As FlowRun.attempt_started_at.
             */
            attempt_started_at: string | null;
            /** Format: date-time */
            end_at: string | null;
            /** @description Copied from the FlowRun it derives from; same rules as FlowRun.attempts. */
            attempts: components["schemas"]["RunAttempt"][] | null;
        };
        Etl: {
            id: string;
            name: string;
            flow_name: string;
            description: string | null;
            tags: string[];
            paused: boolean;
            schedule: components["schemas"]["Schedule"] | null;
            parameters: {
                [key: string]: unknown;
            };
            last_run: components["schemas"]["FlowRun"] | null;
            recent: components["schemas"]["RecentRun"][];
            /** Format: date-time */
            next_run_at: string | null;
            schedule_inactive: boolean;
            /** @description processes appears in parameter_openapi_schema.properties; gates "Re-run from failed process" */
            accepts_processes: boolean;
            /** @description A deep link into the orchestrator's own UI, or null when none is configured. */
            external_url: string | null;
            /** @description The ETL whose completed run starts this one, when an orchestrator automation chains them; only ETLs in the same list are named. */
            triggered_by: components["schemas"]["EtlTrigger"] | null;
            /** @description The ETLs this one's completed run starts, sorted; only ETLs in the same list. */
            triggers: string[];
            /** @description When the ETL was archived in Periplo, by whom and why; null for an active one. An archived ETL is left out of the list's summary and history; its live runs stay in running. */
            archived: components["schemas"]["ArchiveMark"] | null;
        };
        /** @description Where a running run is right now: its process, step, and position among them. total counts processes seen so far in this run, not the deployment's typical process count (documented limitation). */
        EtlCurrent: {
            process: string | null;
            step: string | null;
            index: number;
            total: number;
        };
        RunningRun: {
            id: string;
            name: string;
            etl: string;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            /** Format: date-time */
            start_at: string | null;
            /**
             * Format: date-time
             * @description As FlowRun.attempt_started_at.
             */
            attempt_started_at: string | null;
            /**
             * Format: date-time
             * @description When it was due to start. For a run that has not started (no start time; PENDING here), it says how long the run has waited: the console calls it stuck once it is more than an hour past it.
             */
            expected_start_at: string | null;
            /**
             * Format: date-time
             * @description As FlowRun.waiting_since.
             */
            waiting_since: string | null;
            created_by: string | null;
            /** @enum {string} */
            trigger: "scheduled" | "manual" | "automation";
            current: components["schemas"]["EtlCurrent"] | null;
            /** @description Median duration of the deployment's COMPLETED entries in recent. */
            typical_seconds: number | null;
        };
        EtlUpcoming: {
            etl: string;
            /** Format: date-time */
            expected_start_at: string;
        };
        EtlHistoryBucket: {
            /** Format: date-time */
            start: string;
            completed: number;
            failed: number;
            running: number;
        };
        /** @description One window of the dashboard's pulse: bucketed run counts, oldest to newest. */
        EtlHistory: {
            /** @enum {string} */
            interval: "1h" | "1d";
            buckets: components["schemas"]["EtlHistoryBucket"][];
            /** @description SCHEDULED runs due in the next 6h, at most 50, soonest first. */
            upcoming: components["schemas"]["EtlUpcoming"][];
            median_seconds: number | null;
        };
        Summary: {
            /** @description ETLs with a run going: one that has started (RUNNING, or PENDING with a start time) in running, or a newest recent run that has. A run that has not started is waiting, never running. */
            running: number;
            failed_24h: number;
            completed_24h: number;
            history: components["schemas"]["EtlHistory"];
            history_7d: components["schemas"]["EtlHistory"];
        };
        EtlList: {
            etls: components["schemas"]["Etl"][];
            summary: components["schemas"]["Summary"];
            running: components["schemas"]["RunningRun"][];
            /** @description running was capped at 20 entries. The runs waiting to start appended after the cap (at most 5) do not count, so running can hold up to 25 entries. */
            running_truncated: boolean;
        };
        RunList: {
            runs: components["schemas"]["FlowRun"][];
        };
        RunDetail: components["schemas"]["FlowRun"] & {
            parameters: {
                [key: string]: unknown;
            };
            deployment_id: string | null;
            deployment_name: string | null;
            flow_name: string;
            /** @description state in COMPLETED, FAILED, CANCELLED, CRASHED */
            terminal: boolean;
            /**
             * Format: date-time
             * @description When the run entered its current state: how long it has been cancelling, before a force.
             */
            state_since: string | null;
            /** @description For a run an automation created: the upstream ETL's run that started it, read as that ETL's newest run completed before this one was created, preferring one whose passed parameters match this run's. */
            triggered_by_run: components["schemas"]["RunLink"] | null;
            /** @description For a completed run: each downstream ETL's run its automations created after it ended, the first per downstream ETL. A downstream ETL with none did not run. */
            triggered_runs: components["schemas"]["RunLink"][];
        };
        /** @description A run of another ETL a run is chained to. */
        RunLink: {
            etl: string;
            run_id: string;
            run_name: string;
        };
        LogEntry: {
            id: string;
            /** Format: date-time */
            timestamp: string;
            level: number;
            level_name: string;
            message: string;
            /** @description Starts with one of PERIPLO_ETL_LOG_NOISE's prefixes; folded by default in the web. */
            noise: boolean;
            /** @description Opaque id of the step or process that logged the line (as in RunTasks); null for run-level lines. */
            task_run_id?: string | null;
        };
        /** @enum {string} */
        StepState: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING" | "INTERRUPTED";
        /** @description One try of a step that failed and was started again in the same attempt: loom makes a task run each time a step starts, so each try is its own task run. */
        StepTry: {
            /** @description 1 for the first try. */
            index: number;
            task_run_id: string;
            state: components["schemas"]["StepState"];
            /** Format: date-time */
            start_at: string | null;
            /** Format: date-time */
            end_at: string | null;
            duration_seconds: number | null;
        };
        /** @description One step of a process. A step started again after failing is one step: its state and task_run_id are its last try's, its span from its first try's start to its last try's end, and tries lists each; null for a step that ran once. */
        Step: {
            name: string;
            task_run_id: string;
            state: components["schemas"]["StepState"];
            /** Format: date-time */
            start_at: string | null;
            /** Format: date-time */
            end_at: string | null;
            duration_seconds: number | null;
            tries: components["schemas"]["StepTry"][] | null;
        };
        Process: {
            name: string | null;
            task_run_id: string | null;
            state: components["schemas"]["StepState"];
            /** Format: date-time */
            start_at: string | null;
            /** Format: date-time */
            end_at: string | null;
            duration_seconds: number | null;
            expected_steps: number | null;
            steps: components["schemas"]["Step"][];
        };
        GridCell: {
            process: string;
            state: components["schemas"]["StepState"];
            duration_seconds: number | null;
        };
        GridRun: {
            id: string;
            name: string;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            /** Format: date-time */
            start_at: string | null;
            duration_seconds: number;
            cells: components["schemas"]["GridCell"][];
        };
        RunGrid: {
            /** @description Oldest to newest, left to right. */
            runs: components["schemas"]["GridRun"][];
            /** @description Order of first appearance in the most recent run that has any, then any others. */
            processes: string[];
            /** @description A marker, failed-step or mark query hit its hard page cap before exhausting. */
            truncated: boolean;
        };
        Attempt: {
            number: number;
            /** @enum {string} */
            state: "SCHEDULED" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "CRASHED" | "PAUSED" | "CANCELLING";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string | null;
            message: string | null;
            processes: components["schemas"]["Process"][];
        };
        RunTasks: {
            attempts: components["schemas"]["Attempt"][];
            expected_steps_known: boolean;
        };
        StepFacts: {
            reads: string[];
            writes: string[];
            rows: number | null;
            delta_version: number | null;
        };
        StepDetail: {
            step: components["schemas"]["Step"];
            process: string | null;
            facts: components["schemas"]["StepFacts"];
            logs: components["schemas"]["LogPage"];
        };
        LogPage: {
            entries: components["schemas"]["LogEntry"][];
            /** @description Raw timestamp of the last entry, the received `after` if the page was empty, else null. */
            next: string | null;
            /** @description True when the page came full (entries.length == limit). */
            truncated: boolean;
        };
        RunRequest: {
            /** @description null runs with the deployment's own parameters. */
            parameters?: {
                [key: string]: unknown;
            } | null;
        };
        CancelRequest: {
            /**
             * @description Force a run stuck cancelling for 10 minutes to cancelled; it stops nothing still running.
             * @default false
             */
            force: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    executeQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Arrow IPC stream */
            200: {
                headers: {
                    "X-Query-Id": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.apache.arrow.stream": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getQuery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    cancelQuery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested or already terminal */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    describeTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                database: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Table */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sources and discovery state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    startDiscovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovery started or already running */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getTableStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                database: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the Delta log knows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableStats"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getTableHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                database: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest commits, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableHistory"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integration status; never touches the orchestrator */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtlStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listEtls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployments visible to Periplo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtlList"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlGrid: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The most recent non-SCHEDULED runs of the deployment as a process x run matrix, oldest to newest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunGrid"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Ambiguous deployment name (etl_ambiguous) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listEtlRuns: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs, most recent first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Ambiguous deployment name (etl_ambiguous) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    runEtl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Run created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description The orchestrator rejected the request (etl_rejected) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Operating ETLs is disabled (etl_operate_disabled) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Ambiguous deployment name (etl_ambiguous) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    resumeEtlSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every schedule reactivated (and the deployment un-paused, if it was) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Etl"];
                };
            };
            /** @description The deployment has no schedule (etl_rejected) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Operating ETLs is disabled (etl_operate_disabled) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Ambiguous deployment name (etl_ambiguous) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    pauseEtlSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every schedule deactivated (the inverse of loom's failure hook) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Etl"];
                };
            };
            /** @description The deployment has no schedule (etl_rejected) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Operating ETLs is disabled (etl_operate_disabled) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Ambiguous deployment name (etl_ambiguous) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    archiveEtl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description Archived in Periplo; nothing changes in the orchestrator. One already archived keeps its first mark */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveState"];
                };
            };
            /** @description Archiving is not allowed to this caller (etl_archive_disabled by default) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A reason longer than 500 characters */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    restoreEtl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restored; one that was not archived is left as it is. The orchestrator is not asked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveState"];
                };
            };
            /** @description Archiving is not allowed to this caller (etl_archive_disabled by default) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Integration off (etl_not_configured), or a deployment hidden from the caller (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    cancelEtlRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRequest"];
            };
        };
        responses: {
            /** @description The run read back: CANCELLING while its infrastructure is stopped, or CANCELLED for a run that never started (or one forced) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Operating ETLs is disabled (etl_operate_disabled) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Finished, already cancelling, or not stuck cancelling long enough to force (etl_run_not_cancellable) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    retryEtlRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The same run, scheduled again (AwaitingRetry); its run_count grows when it starts */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Operating ETLs is disabled (etl_operate_disabled) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not failed or crashed, or without a deployment (etl_run_not_retryable) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlRunLogs: {
        parameters: {
            query?: {
                /** @description The `next` of a previous page, opaque to the client; lines with timestamp >= after, ascending. */
                after?: string;
                limit?: number;
                /** @description Repeatable, up to 100 UUIDs. Without it: flow-level lines only. With one or more: those task runs' own lines (several make up a process's scope: its marker plus its steps). */
                task_run?: string[];
                /** @description The orchestrator's own log text search, sent as a quoted phrase; at most 200 characters. */
                q?: string;
                /** @description A floor on log level. */
                min_level?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log page; without `after`, the last `limit` lines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogPage"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlRunTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run's attempts, grouped into processes and steps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTasks"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEtlRunStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                task_run: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One step: its facts and the first page of its own logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepDetail"];
                };
            };
            /** @description Integration off (etl_not_configured) or unknown deployment/run/step (not_found) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The orchestrator is unreachable or rejected the credential (etl_upstream) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
